from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Tuple

from ..config import get_settings
from ..graph.state import FoundationContract
from ..llm import get_llm_client


@dataclass
class ModuleProposal:
    module_name: str
    content: str
    rationale: str


def _usage(response: Any) -> Dict[str, int]:
    return {
        "input_tokens": getattr(response, "input_tokens", 0) or 0,
        "output_tokens": getattr(response, "output_tokens", 0) or 0,
    }


def propose_module_update(
    module_name: str,
    user_request: str,
    foundation: FoundationContract,
) -> Tuple[ModuleProposal, Dict[str, int]]:
    """Layer 2: generate or refine a module implementation."""

    client = get_llm_client()
    summary = foundation.get("summary", "")
    constraints = "\n".join(foundation.get("safety_constraints", []))
    prompt = (
        f"You are a FastCoder-style generator working on module `{module_name}`.\n\n"
        f"User request (do not deviate from this intent — 语义不偏移):\n{user_request}\n\n"
        f"Foundation summary:\n{summary}\n\n"
        "Safety constraints:\n"
        f"{constraints}\n\n"
        "Produce a concise but self-contained Python code snippet or textual plan for this module.\n"
        "Strictly follow the user request; do not add out-of-scope features or change intent (语义不偏移). "
        "Respect the safety constraints and avoid using dangerous primitives."
    )
    response = client.generate_text(prompt)
    proposal = ModuleProposal(
        module_name=module_name,
        content=response.content,
        rationale="Generated by module supervisor based on foundation contract.",
    )
    return proposal, _usage(response)


def score_module_update(
    proposal: ModuleProposal,
    foundation: FoundationContract,
    user_request: str = "",
) -> Tuple[float, List[str], Dict[str, int]]:
    """Layer 2: validate a proposed module update (including semantic alignment with user_request).

    Returns:
        score: float in [0, 1]
        messages: human-readable explanations
        usage: token usage dict
    """
    client = get_llm_client()
    constraints = "\n".join(foundation.get("safety_constraints", []))
    prompt = (
        "You are ModuleSupervisor, validating a single module update.\n\n"
        f"User request (intent to preserve — 语义不偏移):\n{user_request}\n\n"
        f"Module name: {proposal.module_name}\n\n"
        f"Proposed content:\n{proposal.content[:4000]}\n\n"
        "Safety constraints:\n"
        f"{constraints}\n\n"
        "Briefly assess:\n"
        "- 语义不偏移 (Semantic alignment): Does the proposal match the user request above without scope creep or intent drift?\n"
        "- Interface clarity and consistency with typical Python modules.\n"
        "- Obvious correctness issues.\n"
        "- Obvious safety risks.\n"
        "Respond in natural language; an external system will convert this into a numeric score."
    )
    response = client.generate_text(prompt)

    from ..agents.foundation_validators import _heuristic_score

    base = _heuristic_score(response.content)
    messages = [response.content]
    return base, messages, _usage(response)

